name: Build Container

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: [self-hosted, mi3xx, linux-mi325-8gpu-ossci-rad]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Build Iris container
        run: bash .github/scripts/container_build.sh
