name: Iris Single Node Checks

on:
  push:
    branches: [ main, muhaawad/single-node-ci ]
  pull_request:
    branches: [ main, muhaawad/single-node-ci ]
  workflow_dispatch:  

jobs:
  build-image:
    runs-on: [self-hosted, 1mi300x]
    steps:
      - name: Check docker version
        run: |
          ls /opt/
          docker version
          docker buildx version
